version: 6
versionshow: v0.6.0
downloadpathminlen: 88
Port: "18081"
NetworkAddress: 127.0.0.1
Debug: false
PPListDir: /root/sds/rsnode/peers
AccountDir: /root/sds/rsnode/accounts
StorehousePath: /root/sds/rsnode/storage
DownloadPath: /root/sds/rsnode/download
P2PAddress: stsdsaddress
P2PPassword: "12345678"
WalletAddress: staddress
WalletPassword: "12345678"
AutoRun: true
Internal: false
IsWallet: true
IsLimitDownloadSpeed: false
LimitDownloadSpeed: 0
IsLimitUploadSpeed: false
LimitUploadSpeed: 0
ChainId: tropos-3
Token: ustos
StratosChainUrl: https://rest-tropos.thestratos.org:443
StreamingCache: false
RestPort: ""
InternalPort: ""
TrafficLogInterval: 10
SPList:
- P2PAddress: 
  P2PPublicKey: 
  NetworkAddress: 13.58.35.167:8888
- P2PAddress: 
  P2PPublicKey: 
  NetworkAddress: 3.8.63.42:8888
- P2PAddress: 
  P2PPublicKey: 
  NetworkAddress: 44.230.101.227:8888
- P2PAddress: 
  P2PPublicKey: 
  NetworkAddress: 52.69.100.177:8888
